language: node_js

node_js:
   - node
sudo: true
dist: trusty

branches:
   only:
      - master # will only build for master branch commits

before_script: # commands to run before the build step
   - npm install -g --silent @angular/cli

script: # the build step
   - ng build -bh "https://bielik20.github.io/LazyForms/"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: dist
  on:
    branch: master

notifications:
  email: # only receive email when the build status changes (someone broke the build!)
    on_failure: change
    on_success: change
